### PR TITLE
#8 footer component

### LINKED ISSUE #8: Create Footer component from Figma Design
The goal of this issue is to design and implement the Footer Section for the landing page. The Footer Section is located at the bottom.

**Visual Reference**
Footer

### PR DESCRIPTION
**Pull request by edidee**
Fixes  world-wide-techies/annon_chat#8
footer-section

### CODE REVIEW

**Comment by edidee** [comment]
footer_component

**Review by Oyinbrakemigrace — APPROVED** [review]
LG

**Review by Remi-dee — CHANGES_REQUESTED** [review]
Could you use a regular function for the components rather than using arrow function.

**Comment by edidee** [comment]
I have made the changes

**Review by Remi-dee — APPROVED** [review]
LG

**Pull request merged**
