### PR TITLE
Features component

### LINKED ISSUE #4: Create Features Section component from Figma Design
**Description**
The goal of this issue is to implement the Features Section for the landing page. The Features Section will showcase key functionalities and services offered by the website, providing visitors with an overview of the platform's capabilities.

**Visual Reference**
Features Section

### PR DESCRIPTION
**Pull request by Oyinbrakemigrace**

### CODE REVIEW

**Comment by Oyinbrakemigrace** [comment]
features

**Review by Remi-dee — CHANGES_REQUESTED** [review]
Could we have  component files in a component directory?

**Comment by Oyinbrakemigrace** [comment]
> Could we have component files in a component directory?

Done

**Review by Remi-dee — APPROVED** [review]

**Review by annonymousauthority — APPROVED** [review]
Seen

**Pull request merged**
