### PR TITLE
Setup Tailwind config with custom colors, fonts, and font families

### PR DESCRIPTION
**Pull request by xosnrdev**
## Description
This PR includes updates to the Tailwind configuration file to set up the design custom colors, fonts, and font families for our application.

### CODE REVIEW

**Review by annonymousauthority — CHANGES_REQUESTED** [review]
We could remove the body style in the global CSS leaving just tailwind configuration classes

**Comment by xosnrdev** [comment]
> We could remove the body style in the global CSS leaving just tailwind configuration classes

Alright

**Review by annonymousauthority — APPROVED** [review]
LG

**Review by Remi-dee — APPROVED** [review]
LG

**Pull request merged**
