### PR TITLE
6 create testimonial section from figma design

### LINKED ISSUE #6: Create Testimonial Section from Figma Design
**Description**
The purpose of this issue is to create the Testimonial Section for the landing page. The Testimonial Section will feature positive feedback and reviews from satisfied users, adding credibility and trust to the platform.

**Visual Reference**
Testimonials

### PR DESCRIPTION
**Pull request by Remi-dee**
## This PR closes
- #6 

### Description 
Created testimonial session from figma

### View
testimonial

### CODE REVIEW

**Review by Oyinbrakemigrace — APPROVED** [review]
I'm freaked out by the number of commits.

**Review by Oyinbrakemigrace — CHANGES_REQUESTED** [review]
The size of the heading text for the component you worked on is smaller than what the design shows.

**Comment by Remi-dee** [comment]
> I'm freaked out by the number of commits.

Yea, Had a horrible incident, so i commit on Pomodoro technique now, for backup of code changes. I will clean that up now no worries

**Comment by Remi-dee** [comment]
This PR needs to be closed for Clean up

**Comment by Remi-dee** [comment]
> The size of the heading text for the component you worked on is smaller than what the design shows.

It is the same size property with the one on figma, we will optimize that when we start working on responsiveness on multiple screen

**Pull request closed without merging**
